# Generated by Django 3.1.1 on 2021-11-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('date_of_enrollment', models.DateField(auto_now_add=True)),
                ('quiz_score', models.IntegerField(default=0)),
                ('python_entry_level', models.CharField(choices=[('pass', 'PASS'), ('fail', 'FAIL')], default='pass', max_length=4)),
                ('aws_practitioner_exam', models.CharField(choices=[('pass', 'PASS'), ('fail', 'FAIL')], default='pass', max_length=4)),
                ('python_associate_exam', models.CharField(choices=[('pass', 'PASS'), ('fail', 'FAIL')], default='pass', max_length=4)),
                ('blockchain_exam', models.CharField(choices=[('pass', 'PASS'), ('fail', 'FAIL')], default='pass', max_length=4)),
                ('aws_ml_exam', models.CharField(choices=[('pass', 'PASS'), ('fail', 'FAIL')], default='pass', max_length=4)),
                ('dissertation', models.CharField(default='pass', max_length=50)),
                ('date_of_graduation', models.DateField(auto_now_add=True)),
                ('job_placement', models.CharField(max_length=100)),
            ],
        ),
    ]
