# Generated by Django 3.1.1 on 2021-11-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='date_of_enrollment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='date_of_graduation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
